#!/usr/bin/env python3
"""Vendor the Rust sources the R package needs into bindings/r/src/rust.

`R CMD build` (and so r-universe / CRAN) only sees the bindings/r directory, so
the package must carry its own copy of the Rust code it compiles at install
time.  This script regenerates that copy from the monorepo sources.

Usage: vendor_r.py          regenerate bindings/r/src/rust
       vendor_r.py --check  fail if the committed copy is out of date (CI)
"""
import filecmp
import re
import shutil
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path

root = Path(__file__).resolve().parent.parent
dest = root / "bindings/r/src/rust"

WORKSPACE_TOML = """\
# GENERATED by scripts/vendor_r.py -- do not edit.
[workspace]
members = ["crates/puddin", "bindings/julia"]
resolver = "2"

[workspace.package]
version = "{version}"
edition = "{edition}"
authors = {authors}
license = "{license}"
repository = "{repository}"
keywords = {keywords}
categories = {categories}

[workspace.dependencies]
puddin = {{ path = "crates/puddin" }}
uom = {{ version = "0.36", features = ["f64", "si"] }}
proptest = "1"

[profile.release]
lto = true
"""


def q(items):
    return "[" + ", ".join(f'"{i}"' for i in items) + "]"


def build(out: Path):
    ws = tomllib.loads((root / "Cargo.toml").read_text())["workspace"]["package"]
    (out / "crates/puddin").mkdir(parents=True)
    (out / "bindings/julia").mkdir(parents=True)
    (out / "Cargo.toml").write_text(WORKSPACE_TOML.format(
        version=ws["version"], edition=ws["edition"], authors=q(ws["authors"]),
        license=ws["license"], repository=ws["repository"],
        keywords=q(ws["keywords"]), categories=q(ws["categories"])))
    core = (root / "crates/puddin/Cargo.toml").read_text()
    core = re.sub(r"^readme = .*\n", "", core, flags=re.M)  # README is not vendored
    (out / "crates/puddin/Cargo.toml").write_text(core)
    shutil.copytree(root / "crates/puddin/src", out / "crates/puddin/src")
    shutil.copy(root / "bindings/julia/Cargo.toml", out / "bindings/julia/Cargo.toml")
    (out / "bindings/julia/src").mkdir()
    shutil.copy(root / "bindings/julia/src/lib.rs", out / "bindings/julia/src/lib.rs")
    shutil.copy(root / "bindings/julia/include/puddin.h", out / "puddin.h")
    # Reuse the root lockfile's pins; cargo prunes the packages we don't ship.
    shutil.copy(root / "Cargo.lock", out / "Cargo.lock")
    subprocess.run(["cargo", "metadata", "--format-version", "1",
                    "--manifest-path", str(out / "Cargo.toml")],
                   check=True, stdout=subprocess.DEVNULL)


def diff(a: Path, b: Path):
    d = filecmp.dircmp(a, b, ignore=["target"])
    if d.left_only or d.right_only or d.diff_files:
        return True
    return any(diff(a / s, b / s) for s in d.common_dirs)


if "--check" in sys.argv:
    with tempfile.TemporaryDirectory() as t:
        fresh = Path(t) / "rust"
        build(fresh)
        if not dest.exists() or diff(dest, fresh):
            sys.exit("error: bindings/r/src/rust is stale; run scripts/vendor_r.py")
    print("ok")
else:
    for p in dest.glob("*"):
        if p.name != "target":
            shutil.rmtree(p) if p.is_dir() else p.unlink()
    dest.mkdir(parents=True, exist_ok=True)
    tmp = dest / "_tmp"
    build(tmp)
    for p in tmp.iterdir():
        shutil.move(p, dest / p.name)
    tmp.rmdir()
    print(f"vendored into {dest.relative_to(root)}")
